### ISSUE TITLE
Missing 0.2.2 tag and/or a testable gem

### ISSUE THREAD

**Issue by Flameeyes** [pressly/subexec#11]
Hello,

we'd like to update the subexec package in Gentoo which is currently at version 0.2.1.

Unfortunately the gem file does not come with tests, which makes it unusable for us, so we've been using the git tag of 0.2.1 to download the sources, but for 0.2.2 we miss the tag.

Can you help us?

Thanks,
Diego
@gissues:{"order":70,"status":"backlog"}

**Comment by pkieltyka** [comment]
Hi Diego,

Sure. I have tagged v0.2.2.

The specs seem to run fine for me as well via: bundle exec rake spec

Please let me know what issue you're having running the specs.

Peer

**Comment by Flameeyes** [comment]
What I mean is that if we just extract the .gem file itself, it doesn't come with the specs, which makes it useless for Gentoo packaging.

Thanks for the tagging, I'll bump it in the afternoon.
