### ISSUE TITLE
"'export' is not recognized as ....." on windows xp

### ISSUE THREAD

**Issue by sri-soham** [pressly/subexec#4]
Hello,

While installing mini_magick, subexec was installed as a dependency. I tried out a simple script to test mini_magick and it is failing with this error:
"'export' is not recognized as an internal or external command, operable program or batch file."

Searching through the source code, i found this set of lines 
    def exec
      self.output = `export LANG=#{lang} && #{command} 2>&1`
      self.exitstatus = $?.exitstatus
    end
right at the end of subexec.rb file

As far as my knowledge goes, windows doesn't have any 'export' command and probably that is causing the error. May be an OS check and appropriate change of commands is needed here.

I got around the problem by setting value to the timeout member variable, MiniMagick.timeout = 120. This caused the library to use "spawn" instead of  "exec" and hence no error.

Ruby 1.9.2 [i386-mingw32]
mini_magick [3.3]
subexec [0.1.0]

Thanks.

**Comment by pkieltyka** [comment]
Cool. Thanks for bringing this up ... can you try using the master? I just made a commit. This way you don't have to specify a timeout anymore and it should work https://github.com/nulayer/subexec/commit/0d94f58e7e2706d7cf0d7df4deab580255a27834

**Comment by jarmo** [comment]
I didn't try it, but looking at the commit can't understand how does it fix the Windows "export" command issue when using Ruby < 1.9 then still exec is executed where export command is trying to be ran...

**Comment by sri-soham** [comment]
I didn't try it but looking at the code, i think that you have dropped the check for timeout instead of adding the check for operating system.
Probably you should use the sys-uname gem, http://rubygems.org/gems/sys-uname

**Comment by rmw** [comment]
What's the status on this? Is this working now with the master branch?  Thanks!

**Comment by megatux** [comment]
Hi all!,
  It's working for me with the master branch version but I've forked it yesterday and made a fix for CMD redirection syntax. Works ok here (WinXP 32bits & Win7 64bits).
UPDATE: works with new mini_magick 3.4 version (use subexec 0.2.1)
